#!/bin/bash
#PBS -N GATK_HaplotypeCaller
#PBS -l mem=40g,nodes=1:ppn=10,walltime=18:00:00
#PBS -q queue_name_here
#PBS -m abe -M youremail_address_here
#PBS -o GATK_RunHC.out
#PBS -e GATK_RunHC.err
#PBS -V

#sample name
i=1

wkd=/home/data/thala_project/Rescue_Phase
bamf=$wkd/Bam_file
GATK_Bundle=/home/datacenter/reference/GATKbundle/hg19
vcff=$wkd/VCF_file

BWA=/path/to/bwa
SAMTOOLS=/path/to/samtools
PICARD=/path/to/picard.jar
GATK=/path/to/GenomeAnalysisTK.jar

java -jar $GATK \
    -T HaplotypeCaller \
    -R $GATK_Bundle/ucsc.hg19.fasta \
    -I $bamf/"$i"/modified_"$i".bam \
    --emitRefConfidence GVCF \
    --dbsnp $GATK_Bundle/dbsnp_138.hg19.vcf \
    -o $vcff/"$i"/"$i"_RawVariants.g.vcf
