#!/bin/bash
#PBS -N GATK_Genotyping
#PBS -l mem=40g,nodes=1:ppn=10,walltime=18:00:00
#PBS -q queue_name_here
#PBS -m abe -M youremail_address_here
#PBS -o GATK_GT.out
#PBS -e GATK_GT.err
#PBS -V

wkd=/home/data/thala_project/Rescue_Phase
bamf=$wkd/Bam_file
GATK_Bundle=/home/datacenter/reference/GATKbundle/hg19
vcff=$wkd/VCF_file

BWA=/path/to/bwa
SAMTOOLS=/path/to/samtools
PICARD=/path/to/picard.jar
GATK=/path/to/GenomeAnalysisTK.jar

java -jar $GATK \
    -T GenotypeGVCFs \
    -R $GATK_Bundle/ucsc.hg19.fasta \
#replace this line by all samples    --variant $vcff/Sample_1/Sample_1_RawVariants.g.vcf \#
    --dbsnp $GATK_Bundle/dbsnp_138.hg19.vcf \
    -o $vcff/Joint/All_Genotyping.vcf \
    -nt 1
