#!/bin/bash
#PBS -N GATK_HardFiltering
#PBS -l mem=40g,nodes=1:ppn=10,walltime=18:00:00
#PBS -q queue_name_here
#PBS -m abe -M youremail_address_here
#PBS -o GATK_HardF.out
#PBS -e GATK_HardF.err
#PBS -V

i=1

wkd=/home/data/thala_project/Rescue_Phase
bamf=$wkd/Bam_file
GATK_Bundle=/home/datacenter/reference/GATKbundle/hg19
vcff=$wkd/VCF_file

BWA=/path/to/bwa
SAMTOOLS=/path/to/samtools
PICARD=/path/to/picard.jar
GATK=/path/to/GenomeAnalysisTK.jar
VCFTOOLS=/path/to/vcftools_path

# split
$VCFTOOLS --vcf $vcff/Joint/All_Genotyping.vcf \
         --remove-indels \
         --recode \
         --recode-INFO-all \
         --out $vcff/Joint/All_SNV

$VCFTOOLS --vcf $vcff/Joint/All_Genotyping.vcf \
         --keep-only-indels \
         --recode-INFO-all \
         --recode \
         --out $vcff/Joint/All_INDEL

#SNP hard filtering
java -jar $GATK \
    -T VariantFiltration \
    -R $GATK_Bundle/ucsc.hg19.fasta \
    -V $vcff/Joint/All_SNV.recode.vcf \
    -o $vcff/Joint/HardFiltering_SNV.vcf \
     --filterExpression "QD < 2.0 || MQ < 40.0 || FS > 60.0 || SOR > 3.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0" \
     --filterName "FAILED" \
     --logging_level ERROR

#Indel hard filtering
java -jar $GATK \
    -T VariantFiltration \
    -R $GATK_Bundle/ucsc.hg19.fasta \
    -V $vcff/Joint/All_INDEL.recode.vcf \
    -o $vcff/Joint/HardFiltering_INDEL.vcf \
    --filterExpression "QD < 2.0 || ReadPosRankSum < -8.0 || FS > 200.0 || SOR > 10.0" \
    --filterName "FAILED" \
    --logging_level ERROR

$VCFTOOLS --vcf $vcff/Joint/HardFiltering_SNV.vcf \
         --remove-filtered-all \
         --recode \
         --recode-INFO-all \
         --out $vcff/Joint/PASS_SNP

 $VCFTOOLS --vcf $vcff/Joint/HardFiltering_INDEL.vcf \
          --remove-filtered-all \
          --recode \
          --recode-INFO-all \
          --out $vcff/Joint/PASS_INDEL

