#!/bin/bash
#PBS -N Re_align BAM
#PBS -l mem=40g,nodes=1:ppn=10,walltime=18:00:00
#PBS -q queue_name_here
#PBS -m abe -M youremail_address_here
#PBS -o Re_align BAM.out
#PBS -e Re_align BAM.err
#PBS -V

#--------------------------------------------------------
wkd=/home/data/thala_project/Rescue_Phase
Raw_Bam_file_folder=/home/data/thala_project/Bam_file
THALA_Rescue_code="$wkd"/Thala_Rescue_workflow/Realign_BAM/Thalassemia.py
Rescue_Bam_file_folder="$wkd"/Bam_file

i=16H0060040

echo "Begin to re-align "$i

raw_bam_file="$Raw_Bam_file_folder"/"$i"/"$i".bam
rescue_bam_file="$Rescue_Bam_file_folder"/"$i"/modified_"$i".bam
python $THALA_Rescue_code --bamfile $raw_bam_file --output $rescue_bam_file

echo "Finish "$i
