#!/bin/bash
#PBS -N Thala_Find_Causal
#PBS -l mem=40g,nodes=1:ppn=10,walltime=18:00:00
#PBS -q paedwy
#PBS -m abe -M test@test.com
#PBS -o my.out
#PBS -e my.err
#PBS -V

i=1

#including folder
wkd=/home/data/thala_project/Rescue_Phase
bamf=$wkd/Bam_file
GATK_Bundle=/home/datacenter/reference/GATKbundle/hg19
vcff=$wkd/VCF_file

#software
BWA=/path/to/bwa
SAMTOOLS=/path/to/samtools
PICARD=/path/to/picard.jar
GATK=/path/to/GenomeAnalysisTK.jar
VCFTOOLS=/path/to/vcftools

# For SNP------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
cd "$vcff"/Joint/
mkdir temp
cd "$vcff"/Joint/temp
mkdir SNP

for i in all_samples
do
    $VCFTOOLS --vcf "$vcff"/Joint/HardFiltering_SNP.vcf \
	          --indv "$i" \
	          --recode \
	          --recode-INFO-all \
	          --non-ref-ac-any 1 \
	          --out "$vcff"/Joint/temp/SNP/"$i".SNP.mid
done
# -------------------------------------------------------------------------------------------
cd "$vcff"/Joint
mkdir Prediction

for i in all_samples
do
    python Find_causal.py -db "$wkd"/Thala_Rescue_workflow/Know_Causal_Mutation/Known_substitution.vcf \
                          -ind $vcff/Joint/temp/SNP/"$i".SNP.mid.recode.vcf \
                          -o "$vcff"/Joint/Prediction/SNP_"$i".causal.txt
done
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------

# For INDEL----------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
cd "$vcff"/Joint/temp
mkdir INDEL

for i in all_samples
do
    $VCFTOOLS --vcf "$vcff"/Joint/HardFiltering_INDEL.vcf \
	          --indv "$i" \
	          --recode \
	          --recode-INFO-all \
	          --non-ref-ac-any 1 \
	          --out "$vcff"/Joint/temp/INDEL/"$i".INDEL.mid
done
# -------------------------------------------------------------------------------------------
cd "$vcff"/Joint/Prediction

for i in all_samples
do
    python Find_causal.py -db known_substitution.vcf \
                          -ind $vcff/Joint/temp/INDEL/"$i".INDEL.mid.recode.vcf \
                          -o "$vcff"/Joint/Prediction/INDEL_"$i".causal.txt
done
# -------------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------
